//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fryebooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkRequest()
        {
            this.WorkResponses = new HashSet<WorkRespons>();
        }
    
        public int Id { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Description { get; set; }
        public int ClientId { get; set; }
        public int Estimate { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkRespons> WorkResponses { get; set; }
    }
}
