//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fryebooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkRespons
    {
        public int Id { get; set; }
        public System.DateTime TimeStarted { get; set; }
        public System.TimeSpan TimeWorked { get; set; }
        public string Description { get; set; }
        public int WorkRequestId { get; set; }
        public bool Billable { get; set; }
        public Nullable<int> IncomeId { get; set; }
    
        public virtual Income Income { get; set; }
        public virtual WorkRequest WorkRequest { get; set; }
    }
}
